### ISSUE TITLE
Watermark, id-tjek

### ISSUE THREAD

**Issue by Boye08** [KianFrostholm/FlaxHosting-Filer#8]
når man downloader filerne så når man får flere ind så siger watermarket de spiller der er tætte på hinanden og vis man er længere væk så skriver watermarket bare 1 selv om andre også er inde. Og idpeak virker ikke man kan ikke tjekke ids på andre spillere😁

**Comment by KianFrostholm** [comment]
Det handler om hvilken version af onesync du benytter dig af
